logging:
  level:
    com.demo.activemq: debug

spring:
  activemq:
    in-memory: true
#    broker-url: tcp://localhost:61616
#    user: admin
#    password: admin
    packages:
      trust-all: true
  jms:
    pub-sub-domain: true

server:
  servlet:
    context-path: /person-service


topic-name.person: Demo.Person
